---
name: tests

on:
  pull_request:
    branches:
      - master

env:
  VMWCC_USER: ${{ secrets.VMWCC_USER }}
  VMWCC_PASS: ${{ secrets.VMWCC_PASS }}

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.3

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Golang Tests
      run: go test -v ./...
