---
name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  VMWCC_USER: ${{ secrets.VMWCC_USER }}
  VMWCC_PASS: ${{ secrets.VMWCC_PASS }}

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.4

    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Run Golang Tests
      run: go test -v ./...
